version: "2"

services:

  flask:
    build:
      context: flask
    image: innovationla20e09c94.azurecr.io/aigmail:1.0
    environment:
      - CLIENT_ID=2f872e84-4e7f-4c34-ab47-2b4d99685e5b
      - CLIENT_SECRET=9d086e27-b87d-44c1-83c7-287609af3ba6
      - TOKEN=https://api.fusionfabric.cloud/login/v1/sandbox/oidc/token
    ports:
    - 5001:5001