version: "2"

services:

  flask:
    build:
      context: flask
    environment:
      - CLIENT_ID=XXXX
      - CLIENT_SECRET=YYYY
      - TOKEN=https://api.fusionfabric.cloud/login/v1/sandbox/oidc/token
    ports:
    - 5001:5001